### PR TITLE
add option to set the bitmap for NSIS installer left side

### PR DESCRIPTION
**Pull request by ctracey-nv**
Makes the installer look very nice!

### CODE REVIEW

**Comment by SpecLad** [comment]
Did you send this upstream?

**Comment by ctracey-nv** [comment]
No, I thought we'd review it here ourselves first.  I put it together quickly just to check it.  It needs some cosmetic changes (variable names could be better, should split the installer/uninstaller variables to separate cmake ones).  I'll change it a little bit and update.

**Comment by ctracey-nv** [comment]
I think this is ready to go upstream...  How would you like to do that?  Merge it here first?

**Comment by SpecLad** [comment]
No, upstream first. They might propose modifications.

**Comment by ctracey-nv** [comment]
I posted a patch to cmake-developers@cmake.org as per the contribution guide.
No feedback after a few days, will ping them again if nothing after one week.

Anyone have experience upstreaming to CMake?  Tips?

**Comment by SpecLad** [comment]
> Anyone have experience upstreaming to CMake? Tips?

I did send them a few patches, and got them all accepted. They're usually pretty quick to respond, though I suppose with something as fringe as the NSIS generator a longer delay is to be expected.

One problem I see with your patch is that you didn't add any documentation. You should probably rectify that before they ask you to do it.

**Comment by ctracey-nv** [comment]
The patch was accepted by CMake!  https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=3758af12

We should pick it up and use it once it merges to their master.  Closing this PR.

**Pull request closed without merging**
